INSERT INTO VILLE (nomVille, departement) VALUES
('Nantes', 44),
('Ancenis', 44), 
('Angers', 49),
('Le Mans', 72),
('Saint Nazaire', 44),
('Cholet', 49),
('Saumur', 49),
('Fontevraud', 49),
('Laval', 53),
('Sablé-sur-Sarthe', 72),
('La Flèche', 72),
('La Roche-sur-Yon', 85),
('Challans', 85),
('Fontenay le Comte', 85);